# Generated by Django 3.2.13 on 2022-07-12 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontine',
            name='name',
            field=models.CharField(default='tontine-c2ae23817bdd4f723a6b33427e4dcd5429f452d3', max_length=255, verbose_name='Name of Tontine'),
        ),
        migrations.AlterField(
            model_name='tontinewallet',
            name='wallet_pk',
            field=models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(56)], verbose_name='Stellar wallet of tontine public key'),
        ),
        migrations.AlterField(
            model_name='tontinewallet',
            name='wallet_sk',
            field=models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(56)], verbose_name='Stellar wallet of tontine secret key'),
        ),
    ]
