# Generated by Django 3.2.13 on 2022-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0002_auto_20220712_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontine',
            name='name',
            field=models.CharField(default='tontine-ffbd71c403042071231f24a8deb1dfb8649d4830', max_length=255, verbose_name='Name of Tontine'),
        ),
    ]
