# Generated by Django 3.2.13 on 2022-07-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0003_alter_tontine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontine',
            name='name',
            field=models.CharField(default='tontine-fe35fdbe5c01fe32c17b6fe4a36ed2cf51cb051f', max_length=255, verbose_name='Name of Tontine'),
        ),
    ]
