# Generated by Django 3.2.13 on 2022-07-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0004_alter_tontine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tontine',
            name='name',
            field=models.CharField(default='tontine-e3e944a8165c5f012401080544ccb74f760cc576', max_length=255, verbose_name='Name of Tontine'),
        ),
    ]
