version: "3.8"

services:
  web:
    build: ./test_backend
    ports:
      - "8000:8000"
    volumes:
      - ./test_backend/:/usr/src/test_backend/
    command: gunicorn test_backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - environment/.env
      - .env
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx-2
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/usr/src/test_backend/staticfiles
      - media_volume:/usr/src/test_backend/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
