version: "3.8"

services:
  web:
    build: ./test_backend
    ports:
      - "8000:8000"
    volumes:
      - ./test_backend/:/usr/src/test_backend/
    command: gunicorn test_backend.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - environment/.env.local
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - environment/.env.local.db

volumes:
  postgres_data:
